### ISSUE TITLE
Can this repo run on MacBook? Without GPU.

### ISSUE THREAD

**Issue by shoutOutYangJie** [alanlukezic/d3s#10]
I set ATOM's "use_gpu" as False, but I meet "TypeError: `__cuda_array_interface__` must be a dict"

**Comment by alanlukezic** [comment]
I have not tested the code on the Mac without a GPU. After you set the use_gpu to false you need to modify a few line of code in the pytracking/tracker/segm/segm.py: 
search for the "if self.params.use_gpu" in this file and add similar body in the "else" part of the condition.
