### ISSUE TITLE
pretrained model file format corruption

### ISSUE THREAD

**Issue by zhjw0927** [alanlukezic/d3s#15]
After downloading the pre-training file from the given link, it is corrupted.
Please check it, thank you!

**Comment by lllllqqqq** [comment]
Is this question? AttributeError: 'tuple' object has no attribute 'values'

**Comment by zhjw0927** [comment]
> Is this question? AttributeError: 'tuple' object has no attribute 'values'

can't unzip the *.pth.tar, show file was broken.

**Comment by zhjw0927** [comment]
> Is this question? AttributeError: 'tuple' object has no attribute 'values'

can you provide your pretrained model? Thank you!

**Comment by lllllqqqq** [comment]
This file doesn't need to be unzip?
