### ISSUE TITLE
Dead simple evaluation

### ISSUE THREAD

**Issue by nofreewill42** [alanlukezic/d3s#2]
Is there a basic function given it a picture and a first_state and then giving it the next pictures of a sequence?
I feel like the rabbit hole is too deep and I cannot use this project.
Or how should I use it in a live video feed where the pictures are coming from a RPi to my GPU server?

**Comment by alanlukezic** [comment]
You can check pytracking/vot_wrapper.py to see how the tracker is created and used on a video sequence. In general you have to create tracker instance:
tracker = Segm(params)
Initialize tracker on the first frame: 
tracker.initialize(image, gt_rect)
In all the following frames you call track method to get estimation of the target position:
prediction = tracker.track(image)
