### ISSUE TITLE
Where is the GEM part implemented?

### ISSUE THREAD

**Issue by xiankgx** [alanlukezic/d3s#21]
Dear @alanlukezic , I'm really interested in your wonderful work. However, where is the GEM part of the model implemented? From the ltr folder, it seems "test_dist" is feed in directly from data.

**Comment by alanlukezic** [comment]
During offline network training process the GEM output is simulated by perturbing target groundtruth center and contructing the "test_dist" from the perturbed center position. During tracking it is obtained from the target center estimation given by ATOM DCF.

**Comment by xiankgx** [comment]
Ok, thanks for your enlightenment.
