### ISSUE TITLE
Opinion regarding tracking

### ISSUE THREAD

**Issue by xiankgx** [alanlukezic/d3s#22]
Dear @alanlukezic , the GEM module is the DCF filter which helps the model track an object in addition to segmenting it. What do you think of DCF filter vs a sliding window cross correlation template matching layer as done in some works like SiamFC? I've been trying to use the DCF layer for tracking but don't quite understand how to use it. There is a DCFNet implementation by Foolwood but it's not clear how to use it.

**Comment by alanlukezic** [comment]
In principle you can use any tracker you want (SiamFC, DCFNet, ECO, DiMP ...). Current implementation uses a deep DCF (ATOM), which proved to be very successful and achieved very robust tracking performance.

**Comment by xiankgx** [comment]
Thank you @alanlukezic for your expert advice on this matter. Very much appreciated.
