### ISSUE TITLE
SyntaxError: invalid syntax   @in  TensorList([e1 @ e2 for e1, e2 in zip(self, other)])

### ISSUE THREAD

**Issue by jiaqinxu** [alanlukezic/d3s#32]
File "../pytracking/libs/tensorlist.py", line 97
    return TensorList([e1 @ e2 for e1, e2 in zip(self, other)])
                          ^
SyntaxError: invalid syntax

Is it because I used Cuda10？

**Comment by furkancoskun** [comment]
@jiaqinxu Could you find a solution for this problem?

**Comment by chainfitness** [comment]
The code can be executed properly in cuda11.3, but when I move it to AGX Xavier with cuda10.2, it doesn't work, and encountered the same situation. @jiaqinxu can you help me? @furkancoskun
