### ISSUE TITLE
When will D3Sv2 open source？

### ISSUE THREAD

**Issue by Yang428** [alanlukezic/d3s#41]
Hi, D3S is an excellent work and I'm very interesting in the performance of D3Sv2 on VOT2021 benchmark. I found that the scorce codes of D3S and D3Sv2 on the VOT official web are the same. I wonder when d3sv2 will be open source? I'm looking forward to it.

**Comment by alanlukezic** [comment]
D3S2 is an improved version of the original D3S and has just been accepted as a journal publication. We will release the source code for D3S2 in a couple of days here at this Github repository, probably as a separate branch.

**Comment by Yang428** [comment]
> D3S2 is an improved version of the original D3S and has just been accepted as a journal publication. We will release the source code for D3S2 in a couple of days here at this Github repository, probably as a separate branch.

Okay, thank you! I'm looking forward to it.
